config/routes.rb
Palmistry::Application.routes.draw do
  root 'palmistry#index'

  match '/result' , to:'palmistry#result', via:'get'
  match '/profile', to:'palmistry#profile',via:'get'

  resources :palmistry, param: :access_token, only:[ :create, :new, :show, :index]

end

app/controllers/palmistry_controller.rb
class PalmistryController < ApplicationController
  skip_before_action :verify_authenticity_token ,:only=>[:create]

  def new
  end

  def show
    url_without_pdf = request.url.gsub(/\.pdf\Z/,'')
    @qr_url = RQRCode::QRCode.new(url_without_pdf).to_img.resize(300, 300).to_data_url

    user = User.find_by(access_token: params[:access_token]) if params[:access_token]
    @uname = user.uname
    @userid = user.palm_id
    @marriageable = Marriagable.new(user).result_marry_age
    @twitter_link = user.twitter_link
    feeling_line = FeelingLine.new(user)
    @feeling_love = feeling_line.result_love
    @feeling_happy = feeling_line.result_happy
    @feeling_many_love = feeling_line.result_many_love
    @feeling_slow = feeling_line.result_slow

    life_line = LifeLine.new(user)
    @life_power = life_line.result_power
    @life_live = life_line.result_live

    brain_line = BrainLine.new(user)
    @brain_think = brain_line.result_think
    @brain_life = brain_line.result_life
    @brain_genius = brain_line.result_genius
    @brain_hardworker = brain_line.result_hardworker
    @brain_many_skill = brain_line.result_many_skill
    @brain_speed_think = brain_line.result_speed_think
    @brain_indecision = brain_line.result_indecision

    jupiter_line = JupiterLine.new(user)
    @jupiter_social = jupiter_line.result_social
    @jupiter_reader = jupiter_line.result_reader

    sun_line = SunLine.new(user)
    @sun_skill_until = sun_line.result_skill_until
    @sun_skill = sun_line.result_skill
    @sun_charm = sun_line.result_charm

    mercury_line = MercuryLine.new(user)
    @mercury_money = mercury_line.result_money

    venus_line = VenusLine.new(user)
    @venus_virtuous = venus_line.result_virtuous
    @venus_kind_heart = venus_line.result_kind_heart

    moon_line = MoonLine.new(user)
    @moon_like = moon_line.result_like
    @moon_fatigue = moon_line.result_fatigue

    illness_line = IllnessLine.new(user)
    @illness_breath = illness_line.result_breath
    @illness_blood = illness_line.result_blood
    @illness_head = illness_line.result_head
    @illness_eyes = illness_line.result_eyes
    @illness_stomach = illness_line.result_stomach
    @illness_liver = illness_line.result_liver

    hand_shape = HandShape.new(user)
    @hand_shape_waste = hand_shape.result_waste
    @hand_shape_report = hand_shape.result_report

    life_flow_line = LifeFlowLine.new(user)
    @life_flow = life_flow_line.result_flow

    respond_to do |format|
      format.pdf do
        send_data render_to_pdf, filename: "#{@userid}.pdf", disposition: 'inline'
      end
      format.html
    end
  end

  def create
    user = User.create(uname: params[:uname], sex: params[:sex], marry_age: params[:marriageable])
    #twitter_link_insert(user);
    palm_info_insert(user);

    respond_to do |format|
      if user.save
        format.html { redirect_to "/palmistry/#{user.access_token}" }
        format.json { render action: 'show', status: :created, location: "/palmistry/#{user.access_token}" }
      end
    end
  end

  def profile
  end

  private

  def twitter_link_insert(user)
    twitter_link = params[:twitter_link]
    if ( twitter_link.include?('@himajin315') or twitter_link.include?('@himajin315') ) and !twitter_link.include?('script') then
      user.twitter_link = twitter_link
    end
  end

  def palm_info_insert(user)
    user.palm = Palm.create!({
      feeling_love: params[:feeling],
      life_power: params[:life],
      life_live: params[:life_other],
      brain_think: params[:brain],
      brain_life: params[:brain_life],
      mercury_money: params[:mercury],
      life_flow: params[:life_flow],
      })
    feeling_insert(user);
    brain_insert(user);
    jupiter_insert(user);
    sun_insert(user);
    venus_insert(user);
    moon_insert(user);
    illness_insert(user);
    hand_shape_insert(user);
    user.palm.save!
  end

  def feeling_insert(user)
    if params[:feeling_other].present? then
      user.palm.feeling_happy = params[:feeling_other].has_key?("0")
      user.palm.feeling_many_love = params[:feeling_other].has_key?("1")
      user.palm.feeling_slow = params[:feeling_other].has_key?("2")
    end
  end

  def brain_insert(user)
    if params[:brain_other].present? then
      user.palm.brain_genius = params[:brain_other].has_key?("0")
      user.palm.brain_hardworker = params[:brain_other].has_key?("1")
      user.palm.brain_many_skill = params[:brain_other].has_key?("2")
      user.palm.brain_speed_think = params[:brain_other].has_key?("3")
      user.palm.brain_indecision = params[:brain_other].has_key?("4")
    end
  end

  def jupiter_insert(user)
    if params[:jupiter].present? then
      user.palm.jupiter_social = params[:jupiter].has_key?("0")
      user.palm.jupiter_reader = params[:jupiter].has_key?("1")
    end
  end

  def sun_insert(user)
    if params[:sun] == '2' then
      user.palm.sun_skill_until = true
    else
      user.palm.sun_skill = params[:sun]
    end
    if params[:sun_other].present? then
      user.palm.sun_charm = params[:sun_other].has_key?("0")
    end
  end

  def venus_insert(user)
    if params[:venus].present? then
      user.palm.venus_virtuous = params[:venus].has_key?("0")
      user.palm.venus_kind_heart = params[:venus].has_key?("1")
    end
  end

  def moon_insert(user)
    if params[:moon].present? then
      user.palm.moon_like = params[:moon].has_key?("0")
      user.palm.moon_fatigue = params[:moon].has_key?("1")
    end
  end

  def illness_insert(user)
    if params[:illness].present? then
      user.palm.illness_breath = params[:illness].has_key?("0")
      user.palm.illness_blood = params[:illness].has_key?("1")
      user.palm.illness_head = params[:illness].has_key?("2")
      user.palm.illness_eyes = params[:illness].has_key?("3")
      user.palm.illness_stomach = params[:illness].has_key?("4")
      user.palm.illness_liver = params[:illness].has_key?("5")
    end
  end

  def hand_shape_insert(user)
    if params[:hand_shape].present? then
      if params[:mercury] == '0' then
        user.palm.hand_shape_waste = params[:hand_shape].has_key?("0")
      end
      user.palm.hand_shape_report = params[:hand_shape].has_key?("1")
    end
  end
end

app/helpers/palmistry_helper.rb
module PalmistryHelper
end

app/views/palmistry/_check_box.html.erb
<div class="btn-group" data-toggle="buttons">
  <% list.each_with_index do |info,i| %>
  <label class="btn btn-default">
    <input id=<%= name %> name=<%= name + '[' + i.to_s + ']'%> type="checkbox">
    <%= info %>
  </label>
  <% end %>
</div>

app/views/palmistry/_check_box_images.html.erb
<div class="btn-group" data-toggle="buttons">
  <% list.each_with_index do |info,i| %>
  <% # info[0] => image_name, info[1] => alt, info[2] => caption %>
  <label class="btn btn-default">
    <input id=<%= name %> name=<%= name + '[' + i.to_s + ']'%> type="checkbox"  value=<%= i %>>
    <%= image_tag(info[0], class: "palm-img", alt: info[1]) %>
    <p class="palm-img-caption"><%= info[2]%></p>
  </label>
  <% end %>
</div>

app/views/palmistry/_radio_button.html.erb
<div class="btn-group" data-toggle="buttons">
  <% list.each_with_index do |info,i| %>
  <label class="btn btn-info">
    <input class="btn btn-info" id=<%= name %> name=<%= name %> type="radio" value=<%= i %>>
    <%= info %>
  </label>
  <% end %>
</div>
<br>

app/views/palmistry/_radio_button_images.html.erb
<div class="btn-group" data-toggle="buttons">
  <% list.each_with_index do |info,i| %>
  <% # info[0] => image_name, info[1] => alt, info[2] => caption %>
  <label class="btn btn-info">
    <input class="btn btn-info" id=<%= name %> name=<%= name %> type="radio" value=<%= i %>>
    <%= image_tag(info[0], class: "palm-img", alt: info[1]) %>
    <p class="palm-img-caption"><%= info[2]%></p>
  </label>
  <% end %>
</div>
<br>

app/views/palmistry/appraisal.html.erb
<div class="row">
  <h1 class="page-header">暇人の手相鑑定</h1>
  <div id="click-descriptiono">
    <p>手相の特徴をすべて選択し、鑑定結果をクリックして下さい。
      <br><span id="radio-info">　</span>１つ選択  <span id="check-info">　</span>複数選択可</p>
  </div>

  <form method="post" action=<%= result_path %>>
    <h3>名前</h3>
    <p>あなたの名前を入力して下さい。</p>
    <input type="text" class="form-control" name="uname" placeholder='(例) 山田太郎' required='true'><br />

    <h3>性別</h3>
    <%= render partial: "radio_button", locals: { name: "sex", list: ['男性', '女性'] } %>

    <h3>婚期</h3>
    <select multiple class="form-control" name="marriageable[]">
<% for i in 18...50 do %>
  <option value=<%= i %>><%= i %> 歳</option>
<% end %>
    </select>

    <h3>感情線 <small>- 恋愛 -</small></h3>
    <%= render partial: "radio_button_images", locals: { name: "feeling", list: [
      ['love-sudden.png', '唐突な恋愛', '急に上がる'],
      ['love-slow.png', '落ち着いた恋愛', 'ほぼ直線'],
      ['love-short.png', '消極的な恋愛', '短い(中指の下)'],
      ['love-strong-feel.png', '情が深い', '人差し指の下まで届く'],
      ['love-down.png', '相手の気持ちになれる', '先が下に向いている'],
      ['love-onlyone.png', '一途な恋愛', '人差し指と中指の間に届く']
      ] } %>
    <%= render partial: "check_box_images", locals: { name: "feeling_other", list: [
      ['love-divi.png', '人を幸せにする', '先が分かれてる'],
      ['love-branch.png', '数多くの恋愛をする', '枝分かれが多い'],
      ['love-nature.png', 'おっとりタイプ', '線の始まりが低い(ほぼ真ん中に近い)']
      ] } %>

    <h3>生命線 <small>- 健康 -</small></h3>
    <%= render partial: "radio_button_images", locals: { name: "life", list: [
      ['life-bold.png','生命力は強い','線が太い'],
      ['life-ordinary.png','生命力は弱くない', '線が薄くて中心に向かってる'],
      ['life-weak.png','病気になりやすい', '丸いのがある']
      ] } %>
    <%= render partial: "radio_button_images", locals: { name: "life_other", list: [
      ['life-distance.png','海外など遠くに住む','先が左側に向かってる'],
      ['life-many-place.png','いろいろなところに行く','先が中央に向かってる'],
      ['life-stay-home.png','地元に残る','先が右側に向かってる']
      ] } %>

    <h3>頭脳線 <small>- 思考 -</small></h3>
    <%= render partial: "radio_button_images", locals: { name: "brain", list: [
      ['brain-left.png','論理的に考える','真っ直ぐな線'],
      ['brain-right.png','感覚的に捉える','線が下に向かう'],
      ['brain-average.png','なんても平均的にできる','線が斜め下に向かう'],
      ['brain-short.png','直感タイプ','線が短い(中指の下で止まる)'],
      ['brain-masukake.png','ますかけ線','感情線と頭脳線が一緒になってる']
      ] } %>
    <%= render partial: "radio_button_images", locals: { name: "brain_life", list: [
      ['brain-ordinary.png','常識がある','人差し指の下で分かれる'],
      ['brain-careful.png','慎重派','中指の下で分かれる'],
      ['brain-active.png','行動派','生命線と頭脳戦が離れてる'],
      ['brain-suspicion.png','疑心暗鬼',' 頭脳線が生命線の下から始まる'],
      ] } %>
    <%= render partial: "check_box_images", locals: { name: "brain_other", list: [
      ['brain-genius.png','能力が高い','角がある曲がり方'],
      ['brain-hardworker.png','努力家','生命線から人差し指に向かう線'],
      ['brain-manyskil.png','多才','頭脳線から枝分かれがある'],
      ['brain-speedbrain.png','頭の回転が早い','親指に目がある'],
      ['brain-indecision.png','優柔不断','蛇行している']
      ] } %>


    <h3>木星丘 <small>- 権力 -</small></h3>
    <%= render partial: "check_box_images", locals: { name: "jupiter", list: [
      ['jupiter_social.png','社会的に成功したい','人差し指の下に横線'],
      ['jupiter_reader.png','リーダータイプ','人差し指の下に縦線']
      ] } %>

    <h3>太陽丘 <small>- 出世 -</small></h3>
    <%= render partial: "radio_button_images", locals: { name: "sun", list: [
      ['sun-effort.png','地道な努力','先が左側に向いている'],
      ['sun-brain.png','才能を活かして出世','中央に向かってる'],
      ['sun-nothing.png','才能を活かしきれてない','ほとんど見えない']
      ] } %>
    <%= render partial: "check_box_images", locals: { name: "sun_other", list: [
      ['sun-charm.png','魅力的な人','小指と薬指の間と中指と人差し指の間']
      ] } %>

    <h3>水星丘 <small>- 金運 -</small></h3>
    <%= render partial: "radio_button_images", locals: { name: "mercury", list: [
      ['mercury-nothing.png','お金に困ってる','薄い線がある'],
      ['mercury-not-enough.png','お金は入るが出て行く','複数線がある'],
      ['mercury-enough.png','お金には困ってない','濃い線が一本']
      ] } %>

    <h3>金星丘 <small>- 生命力 -</small></h3>
    <%= render partial: "check_box_images", locals: { name: "venus", list: [
      ['venus-virtue.png','徳がある','下から伸びる線'],
      ['venus-love.png','情が深い','網目状が細かい']
      ] } %>

    <h3>月丘 <small>- 人気 -</small></h3>
    <%= render partial: "check_box_images", locals: { name: "moon", list: [
      ['moon-like.png','好かれやすい','斜めから中央に向かってる'],
      ['moon-fatigue.png','疲れがたまってる','横に線が入る']
      ] } %>

    <h3>病気関係</h3>
    <%= render partial: "check_box_images", locals: { name: "illness", list: [
      ['illness_breath.png','呼吸器系に負担','健康線に丸いのがある'],
      ['illness_blood.png','循環器系に負担','荒い'],
      ['illness_head.png','頭関係の病気','頭脳線に丸いのがある'],
      ['illness_eyes.png','目への負担','薬指の下に丸いのがある'],
      ['illness_stomach.png','消化器科に負担','切れ切れ'],
      ['illness_liver.png','腎臓・肝臓に負担','蛇行']
      ] } %>

    <h3>手の開き</h3>
    <%= render partial: "check_box_images", locals: { name: "hand_shape", list: [
      ['hand-shape-waste.png','浪費家','小指と薬指の開き間の開きが大きい'],
      ['hand_shape_report.png','伝えるのが上手','小指が薬指の第2関節より長い']
      ] } %>

    <h3>人生の流れ</h3>
    <%= render partial: "radio_button_images", locals: { name: "life_flow", list: [
      ['life-flow-family.png','家族からの支援','右寄り'],
      ['life-flow-friends.png','周りからの支援','左寄り'],
      ['life-flow-myself.png','自分の道は自分で切り拓く','中央に一直線']
      ] } %>
    <br>
    <button type="submit" class="btn btn-primary">鑑定結果</button>
  </form>
</div>

app/views/palmistry/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4" id="profile-info">
  <h1 class="page-header"></h1>
  <a href="/palmistry/new"><%= image_tag("top_img.png", class:"img-circle", id:"profile-img")%></a>
  </div>
</div>

app/views/palmistry/profile.html.erb
<h1 class="page-header">プロフィール</h1>
<div class="row">
  <div class="col-sm-7" id="profile-info">
    <p>Twitter:<br> <a href="https://twitter.com/himajin315" target="_blank">himajin315</a></p>
    <p>GitHub :<br> <a href="https://github.com/himajin315/palmistry" target="_blank">himajin315/palmistry</a></p>
    <p>coconala : <br><a href="http://coconala.com/services/7607" target="_blank">【わかりやすさ No.1】☆画像プレゼント☆500円手相鑑定☆貴方の成功のタイミングを手に書きます。</a></p>
    <br>
    <h3>参考文献</h3>
    <div class="bibliography">
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=000000&IS2=1&nou=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=himajin315-22&o=9&p=8&l=as1&m=amazon&f=ifr&ref=qf_sp_asin_til&asins=4537203145" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=4528013401&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=4791614291&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=4812702615&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=490203705X&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=4902037211&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=4813319831&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=4040664841&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=B00BXH0KCM&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
      <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=himajin315-22&o=9&p=8&l=as1&asins=B003XF2M4G&nou=1&ref=tf_til&fc1=000000&IS2=1&lt1=_blank&m=amazon&lc1=0000FF&bc1=000000&bg1=FFFFFF&f=ifr" style="width:120px;height:240px;" scrolling="no" marginwidth="0" marginheight="0" frameborder="0"></iframe>
    </div>
  </div>
  <div class="col-sm-5">
    <%= image_tag("yoshiaki_sq.png", class:"img-circle", id:"profile-img")%>
  </div>
</div>

app/views/palmistry/show.html.erb
<div id="pdf-ryudaisai">
  <h4>[琉大祭用]</h4>
</div>
<h1><%= @uname %> さんの 手相鑑定結果</h1>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">QRコードを表示する</button>
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="result-qrcode">
        <h3>QRコード</h3>
        <center><%= image_tag @qr_url %></center>
      </div>
    </div>
  </div>
</div>

<div class="row" id="result-palmistry">
  <div class="col-sm-12 col-md-6">
    <% if @marriageable.present? then %>
      <div id="result-marriageable">
        <h3>婚期</h3>
        <p>
          <%= @marriageable.html_safe %>
        </p>
      </div>
    <% end %>
    <div id="result-love">
      <h3>恋愛</h3>
      <p>
        <!-- 恋愛 -->
        <% if @feeling_love then %>
          <%= @feeling_love.html_safe %>
        <% end %>
        <% if @feeling_happy then %>
          <%= @feeling_happy.html_safe %>
        <% end %>
        <% if @feeling_many_love then %>
          <%= @feeling_many_love.html_safe %>
        <% end %>
        <% if @sun_charm then %>
          <%= @sun_charm.html_safe %>
        <% end %>
        <% if @venus_kind_heart then %>
          <%= @venus_kind_heart.html_safe %>
        <% end %>
      </p>
    </div>
    <div id="result-money">
    <h3>金銭面</h3>
      <p>
        <% if @mercury_money then %>
          <%= @mercury_money.html_safe %>
        <% end %>
        <% if @hand_shape_waste then %>
          <%= @hand_shape_waste.html_safe %>
        <% end %>
        <% if @sun_skill then %>
          <%= @sun_skill.html_safe %>
        <% end %>
      </p>
    </div>
    <% if @life_live then %>
      <div id="result-live">
        <h3>住む場所</h3>
        <p>
          <%= @life_live.html_safe %>
        </p>
      </div>
    <% end %>
    <div id="result-illness">
      <h3>健康面</h3>
      <p>
        <% if @life_power then %>
          <%= @life_power.html_safe %>
        <% end %>
      </p>
      <ul>
        <% if @moon_fatigue then %>
          <li><%= @moon_fatigue.html_safe %></li>
        <% end %>
        <% if @illness_breath then %>
          <li><%= @illness_breath.html_safe %></li>
        <% end %>
        <% if @illness_blood then %>
          <li><%= @illness_blood.html_safe %></li>
        <% end %>
        <% if @illness_head then %>
          <li><%= @illness_head.html_safe %></li>
        <% end %>
        <% if @illness_eyes then %>
          <li><%= @illness_eyes.html_safe %></li>
        <% end %>
        <% if @illness_stomach then %>
          <li><%= @illness_stomach.html_safe %></li>
        <% end %>
        <% if @illness_liver then %>
          <li><%= @illness_liver.html_safe %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-sm-12 col-md-6">
    <div id="result-character">
      <h3>性格</h3>
      <p>
        <% if @feeling_slow then %>
          <%= @feeling_slow.html_safe %>
        <% end %>
        <% if @brain_life then %>
          <%= @brain_life.html_safe %>
        <% end %>
      </p>
    </div>
    <div id="result-skill">
      <h3>能力</h3>
      <p>
        <% if @brain_hardworker then %>
          <%= @brain_hardworker.html_safe %>
        <% end %>
        <% if @sun_skill_until then %>
          <%= @sun_skill_until.html_safe %>
        <% end %>
        <% if @brain_think then %>
          <%= @brain_think.html_safe %>
        <% end %>
        <% if @brain_indecision then %>
          <%= @brain_indecision.html_safe %>
        <% end %>
        <% if @moon_like then %>
          <%= @moon_like.html_safe %>
        <% end %>
        <% if @brain_many_skill then %>
          <%= @brain_many_skill.html_safe %>
        <% end %>
        <% if @brain_speed_think then %>
          <%= @brain_speed_think.html_safe %>
        <% end %>
        <% if @brain_genius then %>
          <%= @brain_genius.html_safe %>
        <% end %>
        <% if @jupiter_social then %>
          <%= @jupiter_social.html_safe %>
        <% end %>
        <% if @jupiter_reader then %>
          <%= @jupiter_reader.html_safe %>
        <% end %>
        <% if @hand_shape_report then %>
          <%= @hand_shape_report.html_safe %>
        <% end %>
        <% if @venus_virtuous then %>
          <%= @venus_virtuous.html_safe %>
        <% end %>
      </p>
    </div>
    <% if @life_flow then %>
      <div id="result-flow">
        <h3>人生の流れ</h3>
        <p>
          <%= @life_flow.html_safe %>
        </p>
      </div>
    <% end %>

    <% if @twitter_link then %>
      <div id="tiwtter-link">
        <%= @twitter_link.html_safe %>
        <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    <% end %>
  </div>
</div>
<div class="sns-button">
  <a href="https://twitter.com/share" class="twitter-share-button" data-via="himajin315" data-hashtags="暇人手相">Tweetする</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>
<div id="opinion">ご意見・ご要望は<a href="https://twitter.com/himajin315" target="_blank">Twitter:@himajin315</a>までお願いします. </div>
<div id="pdf-qrcode">
  <%= image_tag @qr_url %>  <p>恋愛, 性格, 能力を載せています. それ以外の情報は以下のURLまたは右のQRコードより見ることができます. ※個別に発行されてるQRコードです. 再発行できません.</p>
  <p id="result-url"> http://himajin315.com<%= palmistry_path %> </p>
</div>